exclude: ["README.md"]

remote_theme: just-the-docs/just-the-docs
logo: "/assets/images/olson_logo.png"
color_scheme: cog_website

aux_links:
  "Katie Jobson on GitHub":
    - "//github.com/kjobson-neuro"
aux_links_new_tab: true

title: Katie R. Jobson
description: PhD Student at Temple University

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true

ga_tracking: G-ZP3VYT3TCG
ga_tracking_anonymize_ip: true
